# res://src/core/case.gd
class_name Case extends RefCounted

## @brief Represents a single simulation run (a "case").
##
## Each Case object holds a unique set of input values (InVal instances)
## drawn from the defined input variables (InVar instances), and it will later
## store the corresponding output values (OutVal instances) generated by the simulation.
## It also manages a unique seed for any stochastic processes within the run function.

#region Properties
var case_id: int = -1 ## A unique identifier for this specific simulation case.

## Dictionary mapping InVar StringName (id) to its specific InVal for this case.
var input_values: Dictionary = {} # {StringName: InVal}

## Dictionary mapping OutVar StringName (id) to its specific OutVal for this case.
var output_values: Dictionary = {} # {StringName: OutVal}

var seed: int = 0 ## A repeatable random seed for this case, for use in the run function.
var is_processed: bool = false ## Flag to indicate if this case has been processed by the run function.

# References to global value pools, injected by SimManager
var _in_val_pool_ref: ObjectPool = null
var _out_val_pool_ref: ObjectPool = null
#endregion


#region Initialization
# Parameterless _init for object pooling. Values are set after acquisition.
func _init() -> void:
	# Initial values are set by property defaults or by reset() called by pool.
	# We can call reset() here for consistency if desired, though pool also calls it.
	reset() # Ensures a clean state on direct instantiation too.
#endregion


#region Public Methods
## @brief Sets the value pools to be used when resetting this case.
func set_value_pools(p_in_val_pool: ObjectPool, p_out_val_pool: ObjectPool) -> void:
	_in_val_pool_ref = p_in_val_pool
	_out_val_pool_ref = p_out_val_pool

## @brief Adds an input value (InVal) to this case, associated with its InVar id.
func add_input_value(in_var_id: StringName, val: InVal) -> void:
	if not input_values.has(in_var_id):
		input_values[in_var_id] = val
	else:
		push_warning("Case %d: Input variable '%s' already has a value. Overwriting not allowed by default." % [case_id, in_var_id])


## @brief Retrieves an input value (InVal) for a given InVar id.
func get_input_value(in_var_id: StringName) -> InVal:
	if input_values.has(in_var_id):
		return input_values[in_var_id]
	push_warning("Case %d: Input variable '%s' not found." % [case_id, in_var_id])
	return null


## @brief Adds an output value (OutVal) to this case, associated with its OutVar id.
## This is typically called from the postprocess function.
func add_output_value(out_var_id: StringName, val: OutVal) -> void:
	if not output_values.has(out_var_id):
		output_values[out_var_id] = val
	else:
		# Depending on design, we might allow overwriting or multiple values for an output var.
		# For now, let's also warn, similar to inputs.
		push_warning("Case %d: Output variable '%s' already has a value. Overwriting." % [case_id, out_var_id])
		output_values[out_var_id] = val # Allow overwrite for now, can be changed


## @brief Retrieves an output value (OutVal) for a given OutVar id.
func get_output_value(out_var_id: StringName) -> OutVal:
	if output_values.has(out_var_id):
		return output_values[out_var_id]
	# It's normal for output values to not exist before postprocessing, so a warning might be too noisy.
	# print("Case %d: Output variable '%s' not found." % [case_id, out_var_id])
	return null


## @brief Marks the case as processed.
func set_processed(status: bool = true) -> void:
	is_processed = status


## @brief Resets the Case object to a default state for reuse in an object pool.
## If value pools are set, it releases contained InVal/OutVal objects back to them.
func reset() -> void:
	case_id = -1
	seed = 0
	is_processed = false

	# Release InVal objects back to their pool, if the pool reference is set.
	if _in_val_pool_ref:
		for inval_key in input_values:
			var inval_to_release: InVal = input_values[inval_key] as InVal
			if inval_to_release: # Ensure it's not null before releasing
				_in_val_pool_ref.release(inval_to_release)
	input_values.clear()

	# Release OutVal objects back to their pool, if the pool reference is set.
	if _out_val_pool_ref:
		for outval_key in output_values:
			var outval_to_release: OutVal = output_values[outval_key] as OutVal
			if outval_to_release: # Ensure it's not null before releasing
				_out_val_pool_ref.release(outval_to_release)
	output_values.clear()

	# Nullify pool references after use in reset? Or keep them for Case's lifetime?
	# For now, keep them. They'll be reset if set_value_pools is called again by SimManager.
	# _in_val_pool_ref = null
	# _out_val_pool_ref = null
#endregion 