# res://src/core/out_val.gd
class_name OutVal extends Val

## @brief Represents a single output value from a specific case.
##
## Inherits from Val and is used to store the results or data points
## generated by a simulation run.

#region Initialization
func _init(p_num_value: Variant = null, p_mapped_value: Variant = null) -> void:
	super(p_num_value, p_mapped_value)
	# Additional OutVal-specific initialization can go here if needed in the future
#endregion 